run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - dogsled
    - errcheck
    - errorlint
    - gci
    - gofmt
    - goimports
    - gosec
    - govet
    - misspell
    - nakedret
    - nilerr
    - revive
    - staticcheck
